import {useState} from "react";
import {DROP_TYPES} from "../utils/hierarchy";
import AssetImage from "../elements/AssetImage";
import ResolvedBackground from "../elements/ResolvedBackground";
const cssValue=v=>typeof v==="number"?`${v}px`:v;
const layoutStyle=layout=>({display:"flex",flexDirection:layout?.direction||"column",gap:cssValue(layout?.gap),padding:layout?.padding,margin:layout?.margin,width:layout?.width,height:layout?.height,minHeight:layout?.minHeight,maxWidth:layout?.maxWidth,flexGrow:layout?.flexGrow,alignItems:layout?.alignItems,justifyContent:layout?.justifyContent,gridTemplateColumns:layout?.columns});

function NewsCarousel({element,data}){const [index,setIndex]=useState(0),items=data.news||[],item=items[index%Math.max(1,items.length)];return <div data-part="carousel" style={{position:"relative",aspectRatio:"12 / 5",...element.styles}}>{item?.image||item?.image_url?<img src={item.image||item.image_url} alt={item.alt||item.title||"Novedad"} style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<div style={{height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:18,padding:24,background:"radial-gradient(circle at 22% 50%,#250422,#030103 58%)"}}><span style={{fontSize:55}}>📣</span><div><b style={{fontFamily:"Bangers,sans-serif",fontSize:32}}>{element.props.emptyTitle}</b><div style={{fontSize:15,color:"#ddd"}}>{element.props.emptyBody}</div></div></div>}{items.length>1&&<><button aria-label="Anterior" onClick={()=>setIndex((index-1+items.length)%items.length)} style={arrow("left")}>‹</button><button aria-label="Siguiente" onClick={()=>setIndex((index+1)%items.length)} style={arrow("right")}>›</button><div style={{position:"absolute",bottom:8,left:0,right:0,textAlign:"center"}}>{items.map((_,i)=><span key={i} style={{display:"inline-block",width:8,height:8,borderRadius:"50%",margin:3,background:i===index?"#ff2d78":"#666"}}/>)}</div></>}</div>}
const arrow=side=>({position:"absolute",[side]:-10,top:"50%",transform:"translateY(-50%)",width:38,height:38,borderRadius:"50%",border:"1px solid #5d2442",background:"#080408eF",color:"#ff2d78",fontSize:35,lineHeight:1,zIndex:2});
function EventCard({element,data}){const e=data.events?.[element.props.binding?.index||0];if(!e)return null;return <div style={{...layoutStyle(element.layout),...element.styles,position:"relative"}}><div style={{width:62,flex:"0 0 62px",border:"1px solid #70204c",borderRadius:10,textAlign:"center",padding:7}}><b style={{color:"#ff2d78",fontSize:16}}>{e.dayName}</b><strong style={{display:"block",fontSize:31}}>{e.day}</strong><span>{e.month}</span></div><div style={{minWidth:0,position:"relative",zIndex:1}}><b style={{fontFamily:"Bangers,sans-serif",fontSize:22,letterSpacing:1}}>{e.title}</b><p style={{margin:"6px 0 13px",fontSize:14}}>{e.subtitle}</p><span style={{fontSize:12}}>◷ {e.time} · ⌖ {e.location}</span></div>{e.image&&<img src={e.image} alt="" style={{position:"absolute",right:-10,bottom:-25,width:"42%",height:"145%",objectFit:"contain",opacity:.75}}/>}</div>}
function Node({element,children,data,editMode,onSelect,selectedId,onMoveElement}){const [over,setOver]=useState(false);if(!element.visible)return null;const select=e=>{if(editMode){e.preventDefault();e.stopPropagation();onSelect?.(element.id)}};const drag={draggable:editMode&&!element.locked,onDragStart:e=>{e.stopPropagation();e.dataTransfer.setData("application/x-designer-element",element.id)},onDragOver:e=>{if(editMode){e.preventDefault();e.stopPropagation();setOver(true)}},onDragLeave:()=>setOver(false),onDrop:e=>{e.preventDefault();e.stopPropagation();setOver(false);const id=e.dataTransfer.getData("application/x-designer-element");if(id&&id!==element.id)onMoveElement?.(id,DROP_TYPES.has(element.type)?element.id:element.parentId,DROP_TYPES.has(element.type)?null:element.id)}};const edit={outline:over?"2px solid #00e5ff":selectedId===element.id?"2px solid #a855f7":editMode?"1px dashed transparent":undefined,outlineOffset:2,cursor:editMode?"grab":undefined};const style={...layoutStyle(element.layout),...element.styles,opacity:element.opacity,...edit};
 if(element.type==="background")return <ResolvedBackground background={element.props.background||{}} onClick={select} {...drag} style={edit}/>;
 if(element.positionMode==="free")Object.assign(style,{position:"absolute",left:element.x,top:element.y,width:element.width,height:element.height,zIndex:element.zIndex});
 if(element.type==="page"||["section","container","column","stack","row","grid","eventsSection"].includes(element.type))return <div onClick={select} {...drag} style={style}>{children}</div>;
 if(element.type==="image"||element.type==="imageButton")return <AssetImage onClick={select} {...drag} src={element.props.src} assetId={element.props.normalAssetId} alt={element.props.alt||element.name} style={style}/>;
 if(element.type==="text")return <div onClick={select} {...drag} style={style}>{element.props.text}</div>;
 if(element.type==="button")return <button onClick={select} {...drag} style={{border:0,...style}}>{element.props.text}</button>;
 if(element.type==="newsCarousel")return <div onClick={select} style={edit}><NewsCarousel element={element} data={data}/></div>;
 if(element.type==="carouselControl"||element.type==="carouselIndicators")return editMode?<div onClick={select} style={{...edit,display:"none"}}/>:null;
 if(element.type==="eventCard")return <div onClick={select} style={edit}><EventCard element={element} data={data}/></div>;
 if(element.type==="navigationBar")return <nav onClick={select} style={{...style,...(element.props.fixed?{position:"sticky",bottom:0,zIndex:100,marginLeft:-14,marginRight:-14}: {})}}>{children}</nav>;
 if(element.type==="navigationItem")return <button onClick={select} style={{border:0,background:"transparent",padding:0,...style}}><img src={element.props.iconAsset} alt={element.props.label} style={{width:"100%",maxWidth:62,height:58,objectFit:"contain",opacity:element.props.active?1:.72}}/>{element.props.active&&<span style={{display:"block",width:7,height:7,borderRadius:"50%",background:"#ffd600",margin:"-3px auto 0"}}/>}</button>;
 return <div onClick={select} style={style}>{children}</div>}
export default function ResponsiveRenderer({document,pageId,data={},editMode=false,onSelect,selectedId,viewportWidth,onMoveElement}){const page=document.pages.find(p=>p.id===pageId)||document.pages[0],elements=page?.elements||[],byParent=new Map();elements.forEach(e=>{const key=e.parentId||null;byParent.set(key,[...(byParent.get(key)||[]),e])});const render=parent=>(byParent.get(parent)||[]).sort((a,b)=>a.zIndex-b.zIndex).map(e=><Node key={e.id} element={e} data={data} editMode={editMode} onSelect={onSelect} selectedId={selectedId} onMoveElement={onMoveElement}>{render(e.id)}</Node>);return <div style={{position:"relative",width:viewportWidth||document.viewport.width,minHeight:document.viewport.height,background:page.background.value,overflow:"auto"}}>{render(null)}</div>}
