import {useRef,useState} from "react";
import {useDesigner} from "../store/designerStore";
import {saveDesignerAsset} from "../assets/assetStore";
import AssetImage from "../elements/AssetImage";
const basics=[["text","T","Texto"],["image","▧","Imagen"],["button","▣","Botón"],["container","□","Contenedor"],["rectangle","▭","Rectángulo"],["circle","○","Círculo"],["line","—","Línea"],["icon","☆","Icono"],["video","▶","Video"],["spacer","↕","Espaciador"]];
const buttons=[["NOTI","/botones/boton_noti.png","novedades"],["MENÚ","/botones/boton_menu.png","menu"],["PANTALLA","/botones/boton_pantalla.png","pantalla"],["JUEGOS","/botones/boton_juegos.png","games"],["ESCENARIO","/botones/boton_escenario.png","escenario"],["PERFIL","/botones/botones_perfil.png","profile"]];
const readAssets=()=>{try{return JSON.parse(localStorage.getItem("bizarren-designer-asset-list-v1"))||[]}catch{return[]}};
export default function ComponentsSidebar(){const d=useDesigner(),input=useRef(null),[tab,setTab]=useState("elements"),[creating,setCreating]=useState(false),[assets,setAssets]=useState(readAssets);const drag=(event,type)=>event.dataTransfer.setData("application/x-designer-library",type),upload=async event=>{const file=event.target.files?.[0];if(!file)return;const id=await saveDesignerAsset(file),next=[...assets,{id,name:file.name}];localStorage.setItem("bizarren-designer-asset-list-v1",JSON.stringify(next));setAssets(next);event.target.value=""};return <aside className="designer-left"><div className="designer-tabs"><button className={tab==="elements"?"active":""} onClick={()=>setTab("elements")}>Elementos</button><button className={tab==="buttons"?"active":""} onClick={()=>setTab("buttons")}>Botones</button><button className={tab==="mine"?"active":""} onClick={()=>setTab("mine")}>Mis componentes</button></div>{tab==="elements"&&<><Library title="ELEMENTOS" items={basics} add={d.addElement} drag={drag}/><div className="asset-section"><div className="panel-title">ASSETS</div><button className="upload-btn" onClick={()=>input.current.click()}>＋ Subir imagen</button><input ref={input} hidden type="file" accept=".png,.jpg,.jpeg,.webp,.svg,image/*" onChange={upload}/><div className="asset-library">{assets.map(asset=><button key={asset.id} draggable onDragStart={event=>{drag(event,"image");event.dataTransfer.setData("application/x-designer-asset",asset.id)}} onClick={()=>d.addElement("image",{assetId:asset.id,name:asset.name})}><AssetImage assetId={asset.id} alt=""/><span>{asset.name}</span></button>)}</div></div></>}{tab==="buttons"&&<><div className="panel-title">BOTONES</div><div className="button-library">{buttons.map(([name,src,route])=><button key={name} draggable onDragStart={event=>{drag(event,"imageButton");event.dataTransfer.setData("application/x-designer-asset",src)}} onClick={()=>d.createImageButton(name,src,{type:"navigate",target:route})}><img src={src} alt={name}/><span>{name}</span></button>)}</div><button className="upload-btn" onClick={()=>setCreating(true)}>＋ Crear botón</button>{creating&&<CreateButton onClose={()=>setCreating(false)}/>}</>}{tab==="mine"&&<><div className="panel-title">MIS COMPONENTES</div>{d.customComponents.length?d.customComponents.map(component=><button className="saved-component" key={component.id} onClick={()=>d.insertComponent(component)}>◇ {component.name}</button>):<p className="library-empty">Seleccioná un elemento y usá “Crear componente reutilizable”.</p>}</>}</aside>}
function Library({title,items,add,drag}){return <><div className="panel-title">{title}</div><div className="component-grid">{items.map(([type,icon,label])=><button key={type} draggable onDragStart={event=>drag(event,type)} onClick={()=>add(type)}><b>{icon}</b><span>{label}</span></button>)}</div></>}
function CreateButton({onClose}){const d=useDesigner(),[name,setName]=useState("Reservar"),[file,setFile]=useState(null);const create=async()=>{if(!file)return;const id=await saveDesignerAsset(file);d.createImageButton(name,id,{type:"none"});onClose()};return <div className="create-button-form"><label>Nombre<input value={name} onChange={event=>setName(event.target.value)}/></label><label>Imagen normal<input type="file" accept="image/*" onChange={event=>setFile(event.target.files?.[0])}/></label><div><button disabled={!file} onClick={create}>Crear</button><button onClick={onClose}>Cancelar</button></div></div>}
