import {useEffect,useRef,useState} from "react";
import {useDesigner} from "../store/designerStore";
import ScreenRenderer from "../renderer/ScreenRenderer";
import {getClientHomeRuntimeData} from "../data/clientHomeData";
import {calculateSnap} from "../utils/snap";
import {clampZoom,fitViewport} from "../utils/viewport";
import {loadDesignerAsset,saveDesignerAsset} from "../assets/assetStore";
import AssetImage from "../elements/AssetImage";

const handles=["nw","n","ne","w","e","sw","s","se"];
const imageTypes=new Set(["image/png","image/jpeg","image/webp","image/svg+xml"]);

export function screenToCanvasCoordinates(clientX,clientY,stage,viewport){const rect=stage.getBoundingClientRect();return {x:(clientX-rect.left)/viewport.zoom,y:(clientY-rect.top)/viewport.zoom}}

function ElementContent({element}){const style={width:"100%",height:"100%",boxSizing:"border-box",display:"flex",alignItems:"center",justifyContent:"center",...element.styles};if(element.type==="image"||element.type==="imageButton")return <AssetImage src={element.props.src} assetId={element.props.assetId||element.props.normalAssetId} alt={element.name} draggable={false} style={style}/>;if(element.type==="video")return <video src={element.props.src} muted controls style={style}/>;if(element.type==="button")return <button style={{...style,border:0}}>{element.props.text}</button>;if(element.type==="line")return <div style={{...style,height:2,background:element.styles.background||"#fff"}}/>;return <div style={style}>{element.props.text}</div>}
function Background({element}){const b=element.props.background||{},[assetUrl,setAssetUrl]=useState(b.asset||"");useEffect(()=>{let objectUrl;if(b.asset){setAssetUrl(b.asset);return}if(b.assetId)loadDesignerAsset(b.assetId).then(record=>{if(record){objectUrl=URL.createObjectURL(record.blob);setAssetUrl(objectUrl)}});return()=>{if(objectUrl)URL.revokeObjectURL(objectUrl)}},[b.asset,b.assetId]);const fit=b.fit||"cover",position=b.position||"center";let background="transparent";if(b.type==="color")background=b.color;if(b.type==="gradient")background=b.gradient;if(b.type==="image"&&assetUrl)background=`url(${assetUrl}) ${position}/${fit} no-repeat`;return <div style={{position:"absolute",inset:0,zIndex:0,background,opacity:b.opacity??1,filter:b.blur?`blur(${b.blur}px)`:undefined,pointerEvents:"none"}}>{b.type==="video"&&<video src={assetUrl} autoPlay loop muted style={{width:"100%",height:"100%",objectFit:fit,objectPosition:position}}/>}<i style={{position:"absolute",inset:0,background:b.overlay||"transparent"}}/></div>}

function CanvasElement({element,scale,spacePressed}){const designer=useDesigner(),[live,setLive]=useState(null),selected=designer.selectedElementId===element.id;if(!element.visible)return null;if(element.type==="background")return <Background element={element}/>;const current={...element,...live};
 const begin=(event,handle="move")=>{if(designer.tool==="hand"||spacePressed.current||event.button===1)return;if(element.locked)return;event.preventDefault();event.stopPropagation();designer.setSelectedElementId(element.id);const stage=event.currentTarget.closest(".designer-stage"),visual=event.currentTarget.getBoundingClientRect(),stageRect=stage.getBoundingClientRect(),visualRect={x:(visual.left-stageRect.left)/scale,y:(visual.top-stageRect.top)/scale,width:visual.width/scale,height:visual.height/scale};const origin={clientX:event.clientX,clientY:event.clientY,x:element.positionMode==="free"?element.x:visualRect.x,y:element.positionMode==="free"?element.y:visualRect.y,width:visualRect.width,height:visualRect.height,ratio:visualRect.width/visualRect.height};
  const move=pointer=>{const dx=(pointer.clientX-origin.clientX)/scale,dy=(pointer.clientY-origin.clientY)/scale;if(handle==="move"){const snapped=calculateSnap({...element,width:origin.width,height:origin.height},{x:origin.x+dx,y:origin.y+dy},designer.page.elements,designer.document.viewport,designer.snapEnabled,scale);setLive({...snapped.position,width:origin.width,height:origin.height});designer.setGuides(snapped.guides);return}let x=origin.x,y=origin.y,width=origin.width,height=origin.height;if(handle.includes("e"))width+=dx;if(handle.includes("s"))height+=dy;if(handle.includes("w")){width-=dx;x+=dx}if(handle.includes("n")){height-=dy;y+=dy}const image=["image","imageButton"].includes(element.type),preserve=image&&((element.props.lockAspectRatio!==false)!==pointer.shiftKey),ratio=element.props.aspectRatio||origin.ratio;if(preserve){if(handle==="n"||handle==="s")width=height*ratio;else height=width/ratio;if(handle.includes("w"))x=origin.x+origin.width-width;if(handle.includes("n"))y=origin.y+origin.height-height}setLive({x:Math.round(x),y:Math.round(y),width:Math.max(12,Math.round(width)),height:Math.max(12,Math.round(height))})};
  const end=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",end);setLive(value=>{const patch=value||{x:origin.x,y:origin.y,width:origin.width,height:origin.height};designer.updateElement(element.id,{...patch,positionMode:"free"},true);return null});designer.setGuides([])};window.addEventListener("pointermove",move);window.addEventListener("pointerup",end)};
 return <div className={`canvas-element ${selected?"selected":""}`} onPointerDown={event=>begin(event)} style={{position:"absolute",left:current.x,top:current.y,width:current.width,height:current.height,transform:`rotate(${current.rotation||0}deg)`,opacity:current.opacity,zIndex:current.zIndex,cursor:element.locked?"not-allowed":"move",touchAction:"none"}}><ElementContent element={current}/>{selected&&!element.locked&&<><span className="element-coordinates">X {Math.round(current.x)} · Y {Math.round(current.y)}</span>{handles.map(handle=><i key={handle} className={`resize-handle handle-${handle}`} onPointerDown={event=>begin(event,handle)}/>)}</>}</div>}

export default function DesignerCanvas(){const designer=useDesigner(),wrap=useRef(null),stage=useRef(null),spacePressed=useRef(false),{zoom,panX,panY}=designer.canvasViewport;
 useEffect(()=>{const editable=target=>["INPUT","TEXTAREA","SELECT"].includes(target?.tagName)||target?.isContentEditable,down=event=>{if(event.code==="Space"&&!editable(event.target)){spacePressed.current=true;event.preventDefault()}},up=event=>{if(event.code==="Space")spacePressed.current=false};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)}},[]);
 const panStart=event=>{if(!(designer.tool==="hand"||spacePressed.current||event.button===1))return;event.preventDefault();const origin={clientX:event.clientX,clientY:event.clientY,x:panX,y:panY};const move=pointer=>designer.setCanvasViewport(value=>({...value,panX:origin.x+pointer.clientX-origin.clientX,panY:origin.y+pointer.clientY-origin.clientY})),end=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",end)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",end)};
 const wheel=event=>{event.preventDefault();if(event.ctrlKey){const rect=wrap.current.getBoundingClientRect(),next=clampZoom(zoom*(event.deltaY<0?1.12:.89)),mouseX=event.clientX-rect.left-rect.width/2,mouseY=event.clientY-rect.top-rect.height/2,ratio=next/zoom;designer.setCanvasViewport({zoom:next,panX:mouseX-(mouseX-panX)*ratio,panY:mouseY-(mouseY-panY)*ratio});return}designer.setCanvasViewport(value=>({...value,panX:value.panX-(event.shiftKey?event.deltaY:event.deltaX),panY:value.panY-(event.shiftKey?0:event.deltaY)}))};
 const drop=async event=>{event.preventDefault();event.stopPropagation();const point=screenToCanvasCoordinates(event.clientX,event.clientY,stage.current,designer.canvasViewport),libraryType=event.dataTransfer.getData("application/x-designer-library"),libraryAsset=event.dataTransfer.getData("application/x-designer-asset"),files=[...event.dataTransfer.files];if(libraryType){const record=libraryAsset&&!/^https?:|^\//.test(libraryAsset)?await loadDesignerAsset(libraryAsset):null;designer.addElement(libraryType,{...point,...record,...(libraryType==="imageButton"?{normalAssetId:libraryAsset}:{assetId:libraryAsset})});return}const file=files.find(item=>imageTypes.has(item.type));if(file){const assetId=await saveDesignerAsset(file),record=await loadDesignerAsset(assetId);designer.addElement("image",{...point,...record,assetId,name:file.name})}};
 const fit=mode=>designer.setCanvasViewport(fitViewport(wrap.current.getBoundingClientRect(),designer.document.viewport,mode));
 return <section ref={wrap} className={`designer-canvas-wrap tool-${designer.tool}`} onPointerDown={panStart} onWheel={wheel} onClick={()=>designer.setSelectedElementId(null)} onDragOver={event=>{if(event.dataTransfer.types.includes("application/x-designer-library")||event.dataTransfer.types.includes("Files"))event.preventDefault()}} onDrop={drop}><div ref={stage} className="designer-stage" style={{width:designer.document.viewport.width,height:designer.document.viewport.height,background:designer.page.background.value,transform:`translate(${panX}px,${panY}px) scale(${zoom})`}} onClick={event=>event.stopPropagation()}>{designer.page.elements.map(element=><CanvasElement key={element.id} element={element} scale={zoom} spacePressed={spacePressed}/>) }{designer.guidesEnabled&&<><span className="center-guide x"/><span className="center-guide y"/></>}{designer.guides.map((guide,index)=><span key={index} className={`snap-guide ${guide.axis}`} style={guide.axis==="x"?{left:guide.value}:{top:guide.value}}/>)}</div><div className="designer-zoom"><button onClick={()=>designer.setCanvasViewport(value=>({...value,zoom:clampZoom(value.zoom-.1)}))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>designer.setCanvasViewport(value=>({...value,zoom:clampZoom(value.zoom+.1)}))}>+</button><button onClick={()=>designer.setCanvasViewport(value=>({...value,zoom:1}))}>100%</button><button onClick={()=>fit("screen")}>Ajustar pantalla</button><button onClick={()=>fit("width")}>Ajustar ancho</button></div></section>}
export function DesignerPreview(){const designer=useDesigner();return <div className="designer-preview" onClick={()=>designer.setPreview(false)}><button onClick={()=>designer.setPreview(false)}>✕ Cerrar</button><div className="designer-preview-scale"><ScreenRenderer document={designer.document} pageId={designer.selectedPageId} data={getClientHomeRuntimeData()}/></div></div>}
