import { createContext,useCallback,useContext,useEffect,useMemo,useRef,useState } from "react";
import { screenById,screensForTarget } from "../importers/screenRegistry";
import {createClientHomeDocument} from "../documents/clientHomeDocument";
import {migrateDocument} from "../migrations/v1ToV2";
import {canReparent,descendantIds} from "../utils/hierarchy";
const StoreContext=createContext(null);
const uid=(p="el")=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const storageKey=(screen,viewport,kind="draft")=>`bizarren-designer-${kind}-${screen}-${viewport.width}x${viewport.height}-v2`;
const blank=screen=>({version:1,target:screen.target,screenId:screen.id,viewport:{...screen.viewport,breakpoint:"desktop"},pages:[{id:`page-${screen.id}`,name:screen.name,background:{type:"color",value:"#08040f"},elements:[]}]});
const readDraft=screen=>{try{const raw=localStorage.getItem(storageKey(screen.id,screen.viewport))||localStorage.getItem(`bizarren-designer-draft-${screen.target}-v1`);const value=JSON.parse(raw);return value?migrateDocument(value):null}catch{return null}};
const initialDocument=screen=>readDraft(screen)||migrateDocument(screen.nativeDocument==="clientHome"?createClientHomeDocument():blank(screen));

export function DesignerProvider({children}){
 const initial=screenById("giant-idle");
 const [target,setTargetState]=useState(initial.target),[selectedScreenId,setSelectedScreenId]=useState(initial.id);
  const [document,setDocument]=useState(()=>initialDocument(initial));
 const [selectedPageId,setSelectedPageId]=useState(()=>document.pages[0].id),[selectedElementId,setSelectedElementId]=useState(null);
 const [zoom,setZoom]=useState(.5),[preview,setPreview]=useState(false),[savedAt,setSavedAt]=useState(null),[previewWidth,setPreviewWidth]=useState(390);
 const [canvasViewport,setCanvasViewport]=useState({zoom:.5,panX:0,panY:0}),[tool,setTool]=useState("select"),[snapEnabled,setSnapEnabled]=useState(true),[guides,setGuides]=useState([]);
 const [customComponents,setCustomComponents]=useState(()=>{try{return JSON.parse(localStorage.getItem("bizarren-designer-components-v1"))||[]}catch{return[]}});
 const history=useRef({past:[],future:[]}),clipboard=useRef(null);
 const screen=screenById(selectedScreenId),page=document.pages.find(p=>p.id===selectedPageId)||document.pages[0],selected=page?.elements.find(e=>e.id===selectedElementId)||null;
 const hasDraft=!!(screen&&localStorage.getItem(storageKey(screen.id,screen.viewport)));
 const commit=useCallback((recipe,record=true)=>setDocument(current=>{const next=typeof recipe==="function"?recipe(current):recipe;if(record&&next!==current){history.current.past.push(current);if(history.current.past.length>60)history.current.past.shift();history.current.future=[]}return next}),[]);
 const updatePage=useCallback((fn,record=true)=>commit(doc=>({...doc,pages:doc.pages.map(p=>p.id===selectedPageId?fn(p):p)}),record),[commit,selectedPageId]);
 const updateElement=useCallback((id,patch,record=true)=>updatePage(p=>({...p,elements:p.elements.map(e=>e.id===id?{...e,...patch,styles:patch.styles?{...e.styles,...patch.styles}:e.styles,props:patch.props?{...e.props,...patch.props}:e.props}:e)}),record),[updatePage]);
 const selectScreen=useCallback(id=>{const next=screenById(id);if(!next)return;setSelectedScreenId(id);const doc=initialDocument(next);setDocument(doc);setSelectedPageId(doc.pages[0].id);setSelectedElementId(null);setSavedAt(null);history.current={past:[],future:[]}},[]);
 const setTarget=useCallback(next=>{setTargetState(next);setPreviewWidth(next==="client"?390:screensForTarget(next)[0].viewport.width);selectScreen(screensForTarget(next)[0].id)},[selectScreen]);
 const importDocument=useCallback(doc=>{const migrated=migrateDocument(doc);commit(migrated);setSelectedPageId(migrated.pages[0].id);setSelectedElementId(null)},[commit]);
 const openDraft=useCallback(()=>{const draft=screen&&readDraft(screen);if(draft){setDocument(draft);setSelectedPageId(draft.pages[0].id);setSelectedElementId(null);history.current={past:[],future:[]}}},[screen]);
 const save=useCallback(()=>{if(!screen)return;localStorage.setItem(storageKey(screen.id,document.viewport),JSON.stringify(document));setSavedAt(new Date())},[document,screen]);
 const publish=useCallback(()=>{if(!screen)return;save();localStorage.setItem(storageKey(screen.id,document.viewport,"published"),JSON.stringify(document))},[document,save,screen]);
 const addElement=useCallback(type=>{const count=page.elements.length,names={text:"Texto",image:"Imagen",button:"Botón",container:"Contenedor",newsCarousel:"Carrusel de novedades",eventsSection:"Próximos eventos",eventCard:"Card de evento",navigationBar:"Navegación",navigationItem:"Acceso de navegación"},base={id:uid(),name:names[type]||type,type,parentId:document.layoutMode==="responsive"?(page.elements.find(e=>e.type==="page")?.id||null):undefined,layout:document.layoutMode==="responsive"?{direction:"column",gap:10,width:"100%"}:undefined,x:120+count*18,y:110+count*18,width:type==="container"?420:260,height:type==="text"?80:type==="button"?64:220,rotation:0,opacity:1,visible:true,locked:false,zIndex:Math.max(0,...page.elements.map(e=>e.zIndex))+1,styles:{color:"#fff",background:type==="container"?"#251138":type==="button"?"#9b2fff":"transparent",fontSize:type==="text"?42:18,fontWeight:700,textAlign:"center",borderRadius:["container","button","newsCarousel","eventCard"].includes(type)?12:0},props:{text:type==="text"?"Nuevo texto":type==="button"?"Botón":"",src:"",binding:type==="newsCarousel"?{source:"news"}:type.includes("event")?{source:"events"}:undefined}};updatePage(p=>({...p,elements:[...p.elements,base]}));setSelectedElementId(base.id)},[document.layoutMode,page,updatePage]);
 const removeElement=useCallback(id=>{const el=page.elements.find(e=>e.id===id);if(!el||el.systemElement)return;const descendants=new Set([id]);let changed=true;while(changed){changed=false;page.elements.forEach(e=>{if(e.parentId&&descendants.has(e.parentId)&&!descendants.has(e.id)){descendants.add(e.id);changed=true}})}if(descendants.size>1&&!window.confirm("Este elemento contiene otros elementos. ¿Eliminar todo el grupo?"))return;updatePage(p=>({...p,elements:p.elements.filter(e=>!descendants.has(e.id))}));setSelectedElementId(null)},[page,updatePage]);
 const duplicateElement=useCallback(id=>{const root=page.elements.find(e=>e.id===id);if(!root)return;const group=[];const collect=parent=>page.elements.filter(e=>e.parentId===parent).forEach(e=>{group.push(e);collect(e.id)});collect(id);const originals=[root,...group],idMap=new Map(originals.map(e=>[e.id,uid()]));const copies=originals.map((e,index)=>({...e,id:idMap.get(e.id),name:index===0?`${e.name} copia`:e.name,parentId:e.id===id?e.parentId:idMap.get(e.parentId),x:typeof e.x==="number"?e.x+24:e.x,y:typeof e.y==="number"?e.y+24:e.y,zIndex:Math.max(0,...page.elements.map(x=>x.zIndex))+index+1,styles:{...e.styles},props:{...e.props},layout:e.layout?{...e.layout}:undefined,source:e.source?{...e.source}:undefined}));updatePage(p=>({...p,elements:[...p.elements,...copies]}));setSelectedElementId(copies[0].id)},[page,updatePage]);
 const reorderElement=useCallback((id,direction)=>{const ordered=[...page.elements].sort((a,b)=>a.zIndex-b.zIndex),at=ordered.findIndex(e=>e.id===id),swap=direction==="up"?at+1:at-1;if(swap<0||swap>=ordered.length)return;[ordered[at],ordered[swap]]=[ordered[swap],ordered[at]];const ranks=new Map(ordered.map((e,i)=>[e.id,i+1]));updatePage(p=>({...p,elements:p.elements.map(e=>({...e,zIndex:ranks.get(e.id)}))}))},[page,updatePage]);
 const moveInHierarchy=useCallback((id,parentId,beforeId=null)=>{if(!canReparent(page.elements,id,parentId))return;updatePage(p=>{const siblings=p.elements.filter(e=>e.parentId===parentId&&e.id!==id).sort((a,b)=>a.zIndex-b.zIndex);const at=beforeId?siblings.findIndex(e=>e.id===beforeId):siblings.length;siblings.splice(at<0?siblings.length:at,0,p.elements.find(e=>e.id===id));const rank=new Map(siblings.map((e,i)=>[e.id,i+1]));return {...p,elements:p.elements.map(e=>e.id===id?{...e,parentId,zIndex:rank.get(e.id)}:rank.has(e.id)?{...e,zIndex:rank.get(e.id)}:e)}})},[page.elements,updatePage]);
 const setPositionMode=useCallback((id,mode,rect)=>updateElement(id,{positionMode:mode,...(mode==="free"?{x:Math.round(rect?.x||0),y:Math.round(rect?.y||0),width:Math.round(rect?.width||200),height:Math.round(rect?.height||80)}:{})}),[updateElement]);
 const convertToImageButton=useCallback(id=>{const el=page.elements.find(e=>e.id===id);if(el?.type!=="image")return;updateElement(id,{type:"imageButton",name:`${el.name} botón`,props:{...el.props,normalAssetId:el.props.assetId||el.props.src,hoverAssetId:"",activeAssetId:"",disabledAssetId:"",lockAspectRatio:el.props.lockAspectRatio!==false,aspectRatio:el.props.aspectRatio||el.width/el.height},action:{type:"none"}})},[page.elements,updateElement]);
 const createImageButton=useCallback((name,normalAssetId,action={type:"none"})=>{const button={id:uid(),name:name||"Botón de imagen",type:"imageButton",parentId:null,positionMode:"free",x:120,y:120,width:180,height:80,rotation:0,opacity:1,visible:true,locked:false,zIndex:Math.max(0,...page.elements.map(e=>e.zIndex))+1,styles:{objectFit:"fill"},props:{normalAssetId,hoverAssetId:"",activeAssetId:"",disabledAssetId:"",lockAspectRatio:true},action};updatePage(p=>({...p,elements:[...p.elements,button]}));setSelectedElementId(button.id)},[page.elements,updatePage]);
 const createComponent=useCallback((id,name)=>{const root=page.elements.find(e=>e.id===id);if(!root)return;const ids=descendantIds(page.elements,id),items=page.elements.filter(e=>e.id===id||ids.has(e.id));const component={id:uid("component"),name:name||root.name,elements:items};setCustomComponents(current=>{const next=[...current,component];localStorage.setItem("bizarren-designer-components-v1",JSON.stringify(next));return next})},[page.elements]);
 const insertComponent=useCallback(component=>{const idMap=new Map(component.elements.map(e=>[e.id,uid()]));const items=component.elements.map(e=>({...structuredClone(e),id:idMap.get(e.id),parentId:idMap.get(e.parentId)||(document.layoutMode==="responsive"?page.elements.find(x=>x.type==="page")?.id:e.parentId),name:e.id===component.elements[0].id?`${e.name} copia`:e.name}));updatePage(p=>({...p,elements:[...p.elements,...items]}));setSelectedElementId(items[0]?.id)},[document.layoutMode,page.elements,updatePage]);
 const undo=useCallback(()=>setDocument(current=>{const prev=history.current.past.pop();if(!prev)return current;history.current.future.push(current);return prev}),[]),redo=useCallback(()=>setDocument(current=>{const next=history.current.future.pop();if(!next)return current;history.current.past.push(current);return next}),[]);
 const addPage=useCallback(()=>{const id=uid("page"),next={id,name:`Pantalla ${document.pages.length+1}`,background:{type:"color",value:"#10061d"},elements:[{id:`background-${id}`,name:"Fondo",type:"background",positionMode:"free",x:0,y:0,width:document.viewport.width,height:document.viewport.height,rotation:0,opacity:1,visible:true,locked:true,systemElement:true,zIndex:0,styles:{},props:{background:{type:"color",color:"#10061d",fit:"cover",position:"center",opacity:1,blur:0,overlay:"transparent"}}}]};commit(d=>({...d,pages:[...d.pages,next]}));setSelectedPageId(next.id);setSelectedElementId(null)},[commit,document.pages.length,document.viewport]);
 const copy=useCallback(()=>{if(selected)clipboard.current=selected},[selected]),paste=useCallback(()=>{if(!clipboard.current)return;const c={...clipboard.current,id:uid(),name:`${clipboard.current.name} copia`,x:clipboard.current.x+20,y:clipboard.current.y+20,styles:{...clipboard.current.styles},props:{...clipboard.current.props}};updatePage(p=>({...p,elements:[...p.elements,c]}));setSelectedElementId(c.id)},[updatePage]);
 useEffect(()=>{if(!page)setSelectedPageId(document.pages[0]?.id)},[document.pages,page]);
 const value=useMemo(()=>({target,setTarget,screen,selectedScreenId,selectScreen,screens:screensForTarget(target),hasDraft,openDraft,importDocument,document,page,selected,selectedPageId,setSelectedPageId,selectedElementId,setSelectedElementId,zoom,setZoom,preview,setPreview,previewWidth,setPreviewWidth,canvasViewport,setCanvasViewport,tool,setTool,snapEnabled,setSnapEnabled,guides,setGuides,customComponents,savedAt,addElement,updateElement,removeElement,duplicateElement,reorderElement,moveInHierarchy,setPositionMode,convertToImageButton,createImageButton,createComponent,insertComponent,addPage,undo,redo,save,publish,copy,paste}),[target,setTarget,screen,selectedScreenId,selectScreen,hasDraft,openDraft,importDocument,document,page,selected,selectedPageId,selectedElementId,zoom,preview,previewWidth,canvasViewport,tool,snapEnabled,guides,customComponents,savedAt,addElement,updateElement,removeElement,duplicateElement,reorderElement,moveInHierarchy,setPositionMode,convertToImageButton,createImageButton,createComponent,insertComponent,addPage,undo,redo,save,publish,copy,paste]);
 const [guidesEnabled,setGuidesEnabled]=useState(true);
 const addFreeElement=useCallback((type,options={})=>{
  const sizes={text:[200,50],image:[200,150],button:[180,60],container:[300,200],rectangle:[200,140],circle:[140,140],line:[220,8],icon:[80,80],video:[320,180],spacer:[100,40]};
  const [width,height]=sizes[type]||[200,120],names={text:"Texto",image:"Imagen",button:"Botón",container:"Contenedor",rectangle:"Rectángulo",circle:"Círculo",line:"Línea",icon:"Icono",video:"Video",spacer:"Espaciador"};
  const ratio=options.aspectRatio||width/height,isImage=["image","imageButton"].includes(type),initialWidth=options.width||(isImage&&options.naturalWidth?Math.min(360,options.naturalWidth):width),initialHeight=options.height||(isImage?initialWidth/ratio:height);
  const element={id:uid(),name:options.name||names[type]||type,type,parentId:options.parentId??null,positionMode:"free",x:Math.round(options.x??80),y:Math.round(options.y??80),width:Math.round(initialWidth),height:Math.round(initialHeight),rotation:0,opacity:1,visible:true,locked:false,zIndex:Math.max(0,...page.elements.map(item=>item.zIndex||0))+1,styles:{color:"#fff",background:["container","rectangle"].includes(type)?"#251138":type==="circle"||type==="button"?"#9b2fff":"transparent",borderRadius:type==="circle"?"50%":type==="button"?10:0,fontSize:type==="text"?32:18,fontWeight:700,textAlign:"center",objectFit:isImage?"fill":"contain"},props:{text:type==="text"?"Nuevo texto":type==="button"?"Botón":type==="icon"?"★":"",src:options.src||"",assetId:options.assetId||"",normalAssetId:options.normalAssetId||"",naturalWidth:options.naturalWidth,naturalHeight:options.naturalHeight,aspectRatio:ratio,lockAspectRatio:isImage},action:{type:"none"}};
  updatePage(current=>({...current,elements:[...current.elements,element]}));setSelectedElementId(element.id);return element.id;
 },[page.elements,updatePage]);
 const reorderVisual=useCallback((id,direction)=>{const movable=page.elements.filter(item=>!item.systemElement).sort((a,b)=>(a.zIndex||0)-(b.zIndex||0)),at=movable.findIndex(item=>item.id===id);if(at<0)return;const [item]=movable.splice(at,1),target=direction==="front"?movable.length:direction==="back"?0:Math.max(0,Math.min(movable.length,at+(direction==="up"?1:-1)));movable.splice(target,0,item);const rank=new Map(movable.map((entry,index)=>[entry.id,index+1]));updatePage(current=>({...current,elements:current.elements.map(entry=>entry.systemElement?{...entry,zIndex:0}:rank.has(entry.id)?{...entry,zIndex:rank.get(entry.id)}:entry)}))},[page.elements,updatePage]);
 const setImageAsBackground=useCallback((id,removeSource=true)=>{const source=page.elements.find(item=>item.id===id);if(!source||!["image","imageButton"].includes(source.type))return;const assetId=source.props.assetId||source.props.normalAssetId||"",asset=source.props.src||(/^https?:|^\//.test(assetId)?assetId:"");updatePage(current=>({...current,elements:current.elements.map(item=>item.type==="background"?{...item,props:{...item.props,background:{...(item.props.background||{}),type:"image",assetId,asset,fit:"cover",position:"center",opacity:1}}}:item).filter(item=>!removeSource||item.id!==id)}));setSelectedElementId(`background-${page.id}`)},[page.elements,page.id,updatePage]);
 value.addElement=addFreeElement;value.setImageAsBackground=setImageAsBackground;value.reorderElement=reorderVisual;value.guidesEnabled=guidesEnabled;value.setGuidesEnabled=setGuidesEnabled;
 return <StoreContext.Provider value={value}>{children}</StoreContext.Provider>
}
export function useDesigner(){const value=useContext(StoreContext);if(!value)throw new Error("useDesigner requiere DesignerProvider");return value}
